# Generated by Django 4.2.1 on 2023-05-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('red', 'worse way'), ('yellow', 'in profress'), ('green', 'satisfactorily')])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lifetime', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractor.conractor')),
            ],
        ),
    ]
